### ISSUE TITLE
need documentation

### ISSUE THREAD

**Issue by umefarooq** [wayneparrott/cordova-plugin-ezar-snapshot#6]
Hi i have used your plugins, snapshot and video overlay in my test project i need documentation to improve my test app, it was available on ezartech.com, any reason for shutting down ezartech and documentation.

**Comment by wayneparrott** [comment]
Let me see if I can port the former squarespace-based documentation to markdown or similar format.

**Comment by umefarooq** [comment]
you can host your documentation on this site for free https://readthedocs.org/ hope this will be really helpful.
